### ISSUE TITLE
Invalid Test in terms of depth (Coccho_78)

### ISSUE THREAD

**Issue by chrisiKern** [flofriday/UEB-Testsuite#16]
Test Coccho_78 in codeb and gesamt...
```
f(a, b, c)
     var sum = a;
     sum = sum + b;
     sum = sum + c;

     var product = a;
     product = product * b;
     product = product * c;

     var result = sum;
     result = result + product;

     return result;
 end; 
 ```
... seems to exceed the maximum depth of an expression (6 - v) if I understand correctly. This means, this would be a test that wouldn't appear in the test cases used by the LVA.

**Comment by flofriday** [comment]
I guess you are right.
The line `result = result + product;` violates that rule, because at that point there are 6 variables visilbe (3 parameter and 3 local variables) which violates that rule.

@Coccho, @Jozott00 can one of you confirm our assumption here?

Moreover, does that mean that we don't have to use the stack for codeb as we can just keep the variables in registers because there are easily 6 registers available at all time?

**Comment by chrisiKern** [comment]
Codeb doesn't necessarily require the usage of the stack, see: https://tuwel.tuwien.ac.at/mod/forum/discuss.php?d=313930

Also, im not sure if it wouldn't already be too deep at line `product = product * b` because the operation itself has like a depth of 2 or something, and we already have 5 variables at that stage. 

EDIT: ok, `product = product * b` only seems to have depth 1 according to @AustrianGam3r, so it's at the line you suggested where it first violates the rule.

**Comment by Jozott00** [comment]
Yes, @Coccho and I thought that local variables were not included in the maximum expression depth, which is probably wrong. (EDIT: [It's for sure wrong](https://tuwel.tuwien.ac.at/mod/forum/discuss.php?d=313930)

And yes, that would mean that we don't need the stack.

**Comment by chrisiKern** [comment]
> Yes, @Coccho and I thought that local variables were not included in the maximum expression depth, which is probably wrong.
> 
> And yes, that would mean that we only need to use the stack for second order functions.

Well the stack is needed in gesamt of course, but actually not at all in codeb.

**Comment by Coccho** [comment]
Well, when I first made the test, I was pretty sure it had a depth of 7 or 8 at some point (I never really 100% got the whole depth concept), but I decided to leave it with the idea of having an "advanced" test for many operations. If the compiler is well made, it will be stable and pass this test anyhow, since the test only needs a few registers despite of the depth (consider that most of the lines use either a local variable or a parameter). The only problem I can see is if the compiler saves local variables as registers instead of on the stack (which is a very bad idea anyhow imho, but it can work for codeb, yes).
That being said, it is a (slightly) false test case (oops), so I'll leave it to you if you want to remove it from the repo. :)

**Comment by Coccho** [comment]
Alternatively, we could simply remove the line
`result = result + product;`
and only have `return result;`.
Would that fix the depth violation?

**Comment by Coccho** [comment]
@chrisiKern @Jozott00 @flofriday What are your thoughts?

**Comment by flofriday** [comment]
I agree that the register limit is kinda stupid and any well made compiler should handle up to 9 registers easily.

However, if a student for whatever reason relies on that limit, we shouldn't punish them. So I think it would be best to change the test to only go to a limit of 6.

**Comment by Coccho** [comment]
Alright.
I pushed a fix, is the depth alright?

**Comment by flofriday** [comment]
Yes I think that should do it. 
Nice work, and thank you again for the tests 👍
